agent: SacAgent
alpha: 0.6
batch_size: 256
beta: 0.4
beta_annealing: 3.0e-07
critic_update_delay: 1
critic_updates_per_step: 20
cuda: 0
ent_coef: 0.2
entropy_tuning: true
env_name: FishMovingTargetSpeedController-v0
eval_episodes_interval: 10
eval_runs: 3
gamma: 0.99
grad_clip: null
gradients_step: 768
hidden_units:
- 256
- 256
huber: 0
layer_norm: 1
log_interval: 10
lr: 0.0003
memory_size: 1000000.0
method: sac
multi_step: 1
num_steps: 100000
per: 1
seed: 0
start_steps: 0
target_drop_rate: 0.005
target_entropy: -1.0
target_update_interval: 1
tau: 0.005
